# Generated by scripts/generate_model_provider_types.py. Do not edit by hand.
from __future__ import annotations

from typing import Literal, TypedDict

ModelProviderKind = Literal['openai-compatible', 'anthropic', 'gemini', 'bedrock-aws-cli']
DataClassification = Literal['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED']


class _ModelProviderModelRequired(TypedDict):
    id: str
    family: str
    context_tokens: int
    input_usd_per_million: float
    output_usd_per_million: float


class ModelProviderModelConfig(_ModelProviderModelRequired, total=False):
    tools: bool
    vision: bool
    structured_output: bool
    latency_score: float
    quality_score: float
    privacy_score: float
    max_data_classification: DataClassification


class _ModelProviderRequired(TypedDict):
    name: str
    kind: ModelProviderKind
    models: list[ModelProviderModelConfig]


class ModelProviderConfig(_ModelProviderRequired, total=False):
    base_url: str
    api_key_env: str
    region: str
    headers: dict[str, str]
