"""Generated by scripts/generate_provider_types.py. Do not edit manually."""
from typing import Literal, TypedDict

from typing_extensions import NotRequired

ProviderKind = Literal["openai-compatible", "ollama", "anthropic", "gemini", "bedrock-aws-cli"]
ProviderDataClassification = Literal["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"]


class ProviderModelConfig(TypedDict):
    id: str
    family: str
    context_tokens: int
    input_usd_per_million: float
    output_usd_per_million: float
    tools: NotRequired[bool]
    vision: NotRequired[bool]
    structured_output: NotRequired[bool]
    latency_score: NotRequired[float]
    quality_score: NotRequired[float]
    privacy_score: NotRequired[float]
    max_data_classification: NotRequired[ProviderDataClassification]


class ModelProviderConfig(TypedDict):
    name: str
    kind: ProviderKind
    models: list[ProviderModelConfig]
    base_url: NotRequired[str]
    api_key_env: NotRequired[str]
    region: NotRequired[str]
    headers: NotRequired[dict[str, str]]
    keep_alive: NotRequired[str]
    num_ctx: NotRequired[int]
    num_gpu: NotRequired[int]
