// Generated by scripts/generate_model_provider_types.py. Do not edit by hand.
package dev.openforge

enum class ModelProviderKind {
    OPENAI_COMPATIBLE,
    ANTHROPIC,
    GEMINI,
    BEDROCK_AWS_CLI,
}

enum class ModelDataClassification {
    PUBLIC,
    INTERNAL,
    CONFIDENTIAL,
    RESTRICTED,
}

data class ModelProviderModelConfig(
    val id: String,
    val family: String,
    val contextTokens: Int,
    val inputUsdPerMillion: Double,
    val outputUsdPerMillion: Double,
    val tools: Boolean = false,
    val vision: Boolean = false,
    val structuredOutput: Boolean = false,
    val latencyScore: Double = 0.5,
    val qualityScore: Double = 0.8,
    val privacyScore: Double = 0.7,
    val maxDataClassification: ModelDataClassification = ModelDataClassification.INTERNAL,
)

data class ModelProviderConfig(
    val name: String,
    val kind: ModelProviderKind,
    val models: List<ModelProviderModelConfig>,
    val baseUrl: String = "",
    val apiKeyEnv: String? = null,
    val region: String? = null,
    val headers: Map<String, String> = emptyMap(),
)
