// Generated by scripts/generate_provider_types.py. Do not edit manually.
package dev.openforge

enum class ProviderKind(val wireValue: String) {
    OpenaiCompatible("openai-compatible"),
    Ollama("ollama"),
    Anthropic("anthropic"),
    Gemini("gemini"),
    BedrockAwsCli("bedrock-aws-cli")
}

enum class ProviderDataClassification(val wireValue: String) {
    Public("PUBLIC"),
    Internal("INTERNAL"),
    Confidential("CONFIDENTIAL"),
    Restricted("RESTRICTED")
}

data class ProviderModelConfig(
    val id: String,
    val family: String,
    val contextTokens: Int,
    val tools: Boolean = false,
    val vision: Boolean = false,
    val structuredOutput: Boolean = false,
    val inputUsdPerMillion: Double,
    val outputUsdPerMillion: Double,
    val latencyScore: Double = 0.5,
    val qualityScore: Double = 0.8,
    val privacyScore: Double = 0.7,
    val maxDataClassification: ProviderDataClassification = ProviderDataClassification.Internal,
)

data class ModelProviderConfig(
    val name: String,
    val kind: ProviderKind,
    val models: List<ProviderModelConfig>,
    val baseUrl: String? = null,
    val apiKeyEnv: String? = null,
    val region: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val keepAlive: String? = null,
    val numCtx: Int? = null,
    val numGpu: Int? = null,
)
