// Generated by scripts/generate_provider_types.py. Do not edit manually.
export type ProviderKind = "openai-compatible" | "ollama" | "anthropic" | "gemini" | "bedrock-aws-cli";
export type ProviderDataClassification = "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED";

export interface ProviderModelConfig {
  id: string;
  family: string;
  context_tokens: number;
  tools?: boolean;
  vision?: boolean;
  structured_output?: boolean;
  input_usd_per_million: number;
  output_usd_per_million: number;
  latency_score?: number;
  quality_score?: number;
  privacy_score?: number;
  max_data_classification?: ProviderDataClassification;
}

export interface ModelProviderConfig {
  name: string;
  kind: ProviderKind;
  base_url?: string;
  api_key_env?: string;
  region?: string;
  headers?: Record<string, string>;
  keep_alive?: string;
  num_ctx?: number;
  num_gpu?: number;
  models: ProviderModelConfig[];
}
