#!/usr/bin/env python3
"""Regenerate the file-level coverage inventory; not a proof of correctness."""
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/audit/file-inventory.md"
FOCUS = {
    "openforge-acp": "Process lifecycle, framing/timeout tests and restart reconciliation",
    "openforge-artifacts": "F11 concurrent writes; quotas, lifecycle locking and crash recovery",
    "openforge-browser": "URL validation, worker isolation and bounded IPC",
    "openforge-cli": "Shared daemon terminal and standalone commands; interactive approvals and recovery",
    "openforge-context": "Ignore-aware index/deltas; incremental persistence and scale",
    "openforge-core": "F12/F13 execution claims/costs; recovery, isolated tools and full-run tests",
    "openforge-cost": "F02 pending reservations and cancellation cleanup",
    "openforge-daemon": "F05/F08 REST/SSE/catalog/config; auth scopes and lifecycle APIs",
    "openforge-events": "Hash-link verification; incremental checkpoints and trusted anchors",
    "openforge-git": "Worktree integration, rollback and cleanup tests",
    "openforge-mcp": "Stdio tools/resources/prompts; adversarial protocol/process tests",
    "openforge-models": "Routing/fallback present; token streaming, embeddings and conformance",
    "openforge-plugins": "Discovery/containment; installation trust and runtime enforcement",
    "openforge-policy": "Capability/autonomy checks; explanations and durable approvals",
    "openforge-protocol": "Protocol v2 and IDs; generated cross-language contracts",
    "openforge-sandbox": "Three backends; live containment, sync, permissions and cleanup",
    "openforge-scheduler": "F04 graph/budget validation; resource placement and retry backoff",
    "openforge-search": "BM25 search; incremental indexes and relevance evaluation",
    "openforge-secrets": "Environment broker; external managers and real revocation",
    "openforge-store": "F01/F03/F12 memory/settlement/claims; migrations and budget transactions",
    "openforge-symbols": "Heuristic graph; parser-backed semantic accuracy",
    "openforge-telemetry": "Bounded metrics; exporters and correlated tracing",
    "sdk-typescript": "F06 RPC/list/catalog/streams; tests and generated contracts",
    "web-console": "F07 creation/planning/live events; lifecycle and browser tests",
    "desktop": "F10 native workspace/version; native packaging and lifecycle controls",
    "vscode-extension": "Task/search/completion client; controls, streams and extension tests",
    "browser-worker": "Playwright URL checks; redirect/DNS/IPv6 and network isolation tests",
    "ui-components": "Shared panels/status; accessibility and visual tests",
}


def focus(path: Path) -> str:
    parts = path.parts
    if parts[0] in {"crates", "packages"}:
        prefix = "Dependency/build contract; " if path.name in {"Cargo.toml", "package.json", "tsconfig.json"} else ""
        return prefix + FOCUS.get(parts[1], "Component integration review")
    return {
        ".github": "F09 reproducible CI/workflow syntax; release/native/evaluation gates",
        "python": "F06 async SDK, Python 3.10 compatibility and stream/error tests",
        "jetbrains": "Minimal native client; settings/timeouts/tasks/completion",
        "runners": "Toolchain compatibility, least privilege and backend smoke tests",
        "schemas": "JSON contracts; semantic validation and generated type parity",
        "evals": "Declarative scenarios; executable harness and thresholds needed",
        "tests": "Protocol/manifest checks; semantic and cross-component fixtures",
        "config": "Default capability policy; approvals and invalid rule diagnostics",
        "plugins": "Built-in manifest; packaging and runtime enforcement",
        "scripts": "Reproducible review tooling",
        "docs": "Architecture/API/audit documentation; verify implementation claims",
        "THIRD_PARTY_LICENSES": "Attribution; reconcile shipped dependencies",
    }.get(parts[0], "Root build/configuration/project policy; compatibility and documentation")


def main() -> None:
    names = subprocess.check_output(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"], cwd=ROOT
    ).decode().split("\0")
    paths = sorted({Path(name) for name in names if name and name != str(OUTPUT.relative_to(ROOT))})
    lines = ["# File-level review inventory", "",
             "Generated by `python3 scripts/audit-inventory.py` from tracked and unignored files. "
             "Build outputs, dependencies and Git internals are excluded. This is a file coverage index "
             "and review focus, not a claim that every defect has been found. "
             "See [the findings](2026-09-20.md) and [runtime/launcher review](2026-09-21-runtime-launcher.md) for evidence, priorities and verification limits.", "",
             f"Files inventoried: **{len(paths)}** (excluding this generated index).", "",
             "| File | Bytes | Lines | Review focus / follow-up |", "| --- | ---: | ---: | --- |"]
    for path in paths:
        data = (ROOT / path).read_bytes()
        lines.append(f"| [{path}](../../{path}) | {len(data)} | {len(data.splitlines())} | {focus(path)} |")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Inventoried {len(paths)} files")


if __name__ == "__main__":
    main()
