#!/usr/bin/env python3
"""Generate cross-SDK model-provider configuration types from the canonical JSON schema."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas" / "model-provider.schema.json"
OUTPUTS = {
    "typescript": ROOT / "packages" / "sdk-typescript" / "src" / "model-provider.generated.ts",
    "python": ROOT / "python" / "openforge_sdk" / "model_provider.py",
    "kotlin": ROOT / "jetbrains" / "src" / "main" / "kotlin" / "dev" / "openforge" / "ModelProviderConfig.kt",
}


def quoted_union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values)


def render_typescript(schema: dict) -> str:
    kinds = schema["properties"]["kind"]["enum"]
    classes = schema["properties"]["models"]["items"]["properties"]["max_data_classification"]["enum"]
    return f'''// Generated by scripts/generate_model_provider_types.py. Do not edit by hand.\n\nexport type ModelProviderKind = {quoted_union(kinds)};\nexport type DataClassification = {quoted_union(classes)};\n\nexport interface ModelProviderModelConfig {{\n  id: string;\n  family: string;\n  context_tokens: number;\n  tools?: boolean;\n  vision?: boolean;\n  structured_output?: boolean;\n  input_usd_per_million: number;\n  output_usd_per_million: number;\n  latency_score?: number;\n  quality_score?: number;\n  privacy_score?: number;\n  max_data_classification?: DataClassification;\n}}\n\nexport interface ModelProviderConfig {{\n  name: string;\n  kind: ModelProviderKind;\n  base_url?: string;\n  api_key_env?: string;\n  region?: string;\n  headers?: Record<string, string>;\n  models: ModelProviderModelConfig[];\n}}\n'''


def render_python(schema: dict) -> str:
    kinds = schema["properties"]["kind"]["enum"]
    classes = schema["properties"]["models"]["items"]["properties"]["max_data_classification"]["enum"]
    kind_literals = ", ".join(repr(value) for value in kinds)
    class_literals = ", ".join(repr(value) for value in classes)
    return f'''# Generated by scripts/generate_model_provider_types.py. Do not edit by hand.\nfrom __future__ import annotations\n\nfrom typing import Literal, TypedDict\n\nModelProviderKind = Literal[{kind_literals}]\nDataClassification = Literal[{class_literals}]\n\n\nclass _ModelProviderModelRequired(TypedDict):\n    id: str\n    family: str\n    context_tokens: int\n    input_usd_per_million: float\n    output_usd_per_million: float\n\n\nclass ModelProviderModelConfig(_ModelProviderModelRequired, total=False):\n    tools: bool\n    vision: bool\n    structured_output: bool\n    latency_score: float\n    quality_score: float\n    privacy_score: float\n    max_data_classification: DataClassification\n\n\nclass _ModelProviderRequired(TypedDict):\n    name: str\n    kind: ModelProviderKind\n    models: list[ModelProviderModelConfig]\n\n\nclass ModelProviderConfig(_ModelProviderRequired, total=False):\n    base_url: str\n    api_key_env: str\n    region: str\n    headers: dict[str, str]\n'''


def render_kotlin(schema: dict) -> str:
    kinds = schema["properties"]["kind"]["enum"]
    classes = schema["properties"]["models"]["items"]["properties"]["max_data_classification"]["enum"]
    kind_entries = ",\n    ".join(value.upper().replace("-", "_") for value in kinds)
    class_entries = ",\n    ".join(classes)
    return f'''// Generated by scripts/generate_model_provider_types.py. Do not edit by hand.\npackage dev.openforge\n\nenum class ModelProviderKind {{\n    {kind_entries},\n}}\n\nenum class ModelDataClassification {{\n    {class_entries},\n}}\n\ndata class ModelProviderModelConfig(\n    val id: String,\n    val family: String,\n    val contextTokens: Int,\n    val inputUsdPerMillion: Double,\n    val outputUsdPerMillion: Double,\n    val tools: Boolean = false,\n    val vision: Boolean = false,\n    val structuredOutput: Boolean = false,\n    val latencyScore: Double = 0.5,\n    val qualityScore: Double = 0.8,\n    val privacyScore: Double = 0.7,\n    val maxDataClassification: ModelDataClassification = ModelDataClassification.INTERNAL,\n)\n\ndata class ModelProviderConfig(\n    val name: String,\n    val kind: ModelProviderKind,\n    val models: List<ModelProviderModelConfig>,\n    val baseUrl: String = "",\n    val apiKeyEnv: String? = null,\n    val region: String? = null,\n    val headers: Map<String, String> = emptyMap(),\n)\n'''


def generated(schema: dict) -> dict[str, str]:
    return {
        "typescript": render_typescript(schema),
        "python": render_python(schema),
        "kotlin": render_kotlin(schema),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    outputs = generated(schema)
    stale: list[str] = []
    for name, path in OUTPUTS.items():
        content = outputs[name]
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        raise SystemExit("stale generated model-provider types: " + ", ".join(stale))


if __name__ == "__main__":
    main()
