#!/usr/bin/env python3
"""Generate cross-SDK model-provider configuration types from the canonical JSON schema."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas" / "model-provider.schema.json"
OUTPUTS = {
    "typescript": ROOT / "packages" / "sdk-typescript" / "src" / "model-provider.generated.ts",
    "python": ROOT / "python" / "openforge_sdk" / "model_provider.py",
    "kotlin": ROOT / "jetbrains" / "src" / "main" / "kotlin" / "dev" / "openforge" / "ModelProviderConfig.kt",
}


def quoted_union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values)


def schema_values(schema: dict) -> tuple[list[str], list[str]]:
    kinds = schema["properties"]["kind"]["enum"]
    classes = schema["properties"]["models"]["items"]["properties"]["max_data_classification"]["enum"]
    return kinds, classes


def render_typescript(schema: dict) -> str:
    kinds, classes = schema_values(schema)
    return f'''// Generated by scripts/generate_model_provider_types.py. Do not edit by hand.

export type ModelProviderKind = {quoted_union(kinds)};
export type DataClassification = {quoted_union(classes)};

export interface ModelProviderModelConfig {{
  id: string;
  family: string;
  context_tokens: number;
  tools?: boolean;
  vision?: boolean;
  structured_output?: boolean;
  input_usd_per_million: number;
  output_usd_per_million: number;
  latency_score?: number;
  quality_score?: number;
  privacy_score?: number;
  max_data_classification?: DataClassification;
}}

export interface ModelProviderConfig {{
  name: string;
  kind: ModelProviderKind;
  base_url?: string;
  api_key_env?: string;
  region?: string;
  headers?: Record<string, string>;
  keep_alive?: string;
  num_ctx?: number;
  num_gpu?: number;
  models: ModelProviderModelConfig[];
}}
'''


def render_python(schema: dict) -> str:
    kinds, classes = schema_values(schema)
    kind_literals = ", ".join(json.dumps(value) for value in kinds)
    class_literals = ", ".join(json.dumps(value) for value in classes)
    return f'''# Generated by scripts/generate_model_provider_types.py. Do not edit by hand.
from __future__ import annotations

from typing import Literal, TypedDict

ModelProviderKind = Literal[{kind_literals}]
DataClassification = Literal[{class_literals}]


class _ModelProviderModelRequired(TypedDict):
    id: str
    family: str
    context_tokens: int
    input_usd_per_million: float
    output_usd_per_million: float


class ModelProviderModelConfig(_ModelProviderModelRequired, total=False):
    tools: bool
    vision: bool
    structured_output: bool
    latency_score: float
    quality_score: float
    privacy_score: float
    max_data_classification: DataClassification


class _ModelProviderRequired(TypedDict):
    name: str
    kind: ModelProviderKind
    models: list[ModelProviderModelConfig]


class ModelProviderConfig(_ModelProviderRequired, total=False):
    base_url: str
    api_key_env: str
    region: str
    headers: dict[str, str]
    keep_alive: str
    num_ctx: int
    num_gpu: int
'''


def render_kotlin(schema: dict) -> str:
    kinds, classes = schema_values(schema)
    kind_entries = ",\n    ".join(value.upper().replace("-", "_") for value in kinds)
    class_entries = ",\n    ".join(classes)
    return f'''// Generated by scripts/generate_model_provider_types.py. Do not edit by hand.
package dev.openforge

enum class ModelProviderKind {{
    {kind_entries},
}}

enum class ModelDataClassification {{
    {class_entries},
}}

data class ModelProviderModelConfig(
    val id: String,
    val family: String,
    val contextTokens: Int,
    val inputUsdPerMillion: Double,
    val outputUsdPerMillion: Double,
    val tools: Boolean = false,
    val vision: Boolean = false,
    val structuredOutput: Boolean = false,
    val latencyScore: Double = 0.5,
    val qualityScore: Double = 0.8,
    val privacyScore: Double = 0.7,
    val maxDataClassification: ModelDataClassification = ModelDataClassification.INTERNAL,
)

data class ModelProviderConfig(
    val name: String,
    val kind: ModelProviderKind,
    val models: List<ModelProviderModelConfig>,
    val baseUrl: String = "",
    val apiKeyEnv: String? = null,
    val region: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val keepAlive: String? = null,
    val numCtx: Int? = null,
    val numGpu: Int? = null,
)
'''


def generated(schema: dict) -> dict[str, str]:
    return {
        "typescript": render_typescript(schema),
        "python": render_python(schema),
        "kotlin": render_kotlin(schema),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    outputs = generated(schema)
    stale: list[str] = []
    for name, path in OUTPUTS.items():
        content = outputs[name]
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        raise SystemExit("stale generated model-provider types: " + ", ".join(stale))


if __name__ == "__main__":
    main()
