#!/usr/bin/env python3
"""Generate provider-config SDK types from schemas/model-provider.schema.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas/model-provider.schema.json"
TARGETS = {
    ROOT / "packages/sdk-typescript/src/provider-config.generated.ts": "ts",
    ROOT / "python/openforge_sdk/provider_config.py": "py",
    ROOT / "jetbrains/src/main/kotlin/dev/openforge/ProviderConfig.kt": "kt",
}


def load_values():
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    kinds = schema["properties"]["kind"]["enum"]
    classifications = schema["$defs"]["model"]["properties"]["max_data_classification"]["enum"]
    return kinds, classifications


def ts(kinds, classifications):
    kind = " | ".join(json.dumps(value) for value in kinds)
    cls = " | ".join(json.dumps(value) for value in classifications)
    return f"""// Generated by scripts/generate_provider_types.py. Do not edit manually.
export type ProviderKind = {kind};
export type ProviderDataClassification = {cls};

export interface ProviderModelConfig {{
  id: string;
  family: string;
  context_tokens: number;
  tools?: boolean;
  vision?: boolean;
  structured_output?: boolean;
  input_usd_per_million: number;
  output_usd_per_million: number;
  latency_score?: number;
  quality_score?: number;
  privacy_score?: number;
  max_data_classification?: ProviderDataClassification;
}}

export interface ModelProviderConfig {{
  name: string;
  kind: ProviderKind;
  base_url?: string;
  api_key_env?: string;
  region?: string;
  headers?: Record<string, string>;
  keep_alive?: string;
  num_ctx?: number;
  num_gpu?: number;
  models: ProviderModelConfig[];
}}
"""


def py(kinds, classifications):
    kind = ", ".join(repr(value) for value in kinds)
    cls = ", ".join(repr(value) for value in classifications)
    return f'''"""Generated by scripts/generate_provider_types.py. Do not edit manually."""
from typing import Literal, TypedDict

from typing_extensions import NotRequired

ProviderKind = Literal[{kind}]
ProviderDataClassification = Literal[{cls}]


class ProviderModelConfig(TypedDict):
    id: str
    family: str
    context_tokens: int
    input_usd_per_million: float
    output_usd_per_million: float
    tools: NotRequired[bool]
    vision: NotRequired[bool]
    structured_output: NotRequired[bool]
    latency_score: NotRequired[float]
    quality_score: NotRequired[float]
    privacy_score: NotRequired[float]
    max_data_classification: NotRequired[ProviderDataClassification]


class ModelProviderConfig(TypedDict):
    name: str
    kind: ProviderKind
    models: list[ProviderModelConfig]
    base_url: NotRequired[str]
    api_key_env: NotRequired[str]
    region: NotRequired[str]
    headers: NotRequired[dict[str, str]]
    keep_alive: NotRequired[str]
    num_ctx: NotRequired[int]
    num_gpu: NotRequired[int]
'''


def kotlin_name(value: str) -> str:
    return "".join(part.capitalize() for part in value.replace("-", "_").split("_"))


def kt(kinds, classifications):
    kind_lines = ",\n".join(
        f'    {kotlin_name(value)}("{value}")' for value in kinds
    )
    cls_lines = ",\n".join(
        f'    {kotlin_name(value.lower())}("{value}")' for value in classifications
    )
    return f'''// Generated by scripts/generate_provider_types.py. Do not edit manually.
package dev.openforge

enum class ProviderKind(val wireValue: String) {{
{kind_lines}
}}

enum class ProviderDataClassification(val wireValue: String) {{
{cls_lines}
}}

data class ProviderModelConfig(
    val id: String,
    val family: String,
    val contextTokens: Int,
    val tools: Boolean = false,
    val vision: Boolean = false,
    val structuredOutput: Boolean = false,
    val inputUsdPerMillion: Double,
    val outputUsdPerMillion: Double,
    val latencyScore: Double = 0.5,
    val qualityScore: Double = 0.8,
    val privacyScore: Double = 0.7,
    val maxDataClassification: ProviderDataClassification = ProviderDataClassification.Internal,
)

data class ModelProviderConfig(
    val name: String,
    val kind: ProviderKind,
    val models: List<ProviderModelConfig>,
    val baseUrl: String? = null,
    val apiKeyEnv: String? = null,
    val region: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val keepAlive: String? = null,
    val numCtx: Int? = null,
    val numGpu: Int? = null,
)
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    kinds, classifications = load_values()
    renderers = {"ts": ts, "py": py, "kt": kt}
    failed = []
    for path, language in TARGETS.items():
        expected = renderers[language](kinds, classifications)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                failed.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if failed:
        print("generated provider types are stale: " + ", ".join(failed))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
