[package]
name = "openforge-secrets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
openforge-protocol = { path = "../openforge-protocol" }
zeroize.workspace = true
tokio.workspace = true
